name: Update Dependencies

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-dependencies:
    name: Update Dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      - name: Install dependencies
        run: npm clean-install
      - name: Update dependencies
        run: scripts/update-dependencies.sh
      - name: Check format
        run: npm run check-format
      - name: Lint
        run: npm run lint
      - name: Check types
        run: npm run check-types
      - name: Commit and push
        run: |
          git config user.email "limits-thymus-0p@icloud.com"
          git config user.name "GitHub Actions"
          if [[ `git status --porcelain package.json package-lock.json` ]]; then
            git add package.json package-lock.json
            git commit -m "update dependencies"
            git push
          fi
